### ISSUE TITLE
Reasons for the rain/snow severity configuration

### ISSUE THREAD

**Issue by boyang9602** [Castiel-Lee/robustness_pc_detector#1]
Hi,

Thank you for your great work. I am doing some similar work. I wonder what the reasons are for the choices severity of rain and snow. 
> rain in {5.0, 15.0, 50.0, 150.0, 500.0} and snow in {0.5, 1.5, 5.0, 15.0, 50.0}.

Regards,
Bo Yang

**Comment by Castiel-Lee** [comment]
Hello Bo,

The parameters of rain are based on the investigation of rainfall rate in
mm/hr. So do snow parameters. Also, such settings optimize the
simulation to real-world scenarios as depicted in the paper.

I hope it helps.

**Comment by boyang9602** [comment]
Hi Castiel,

Thank you for your quick response. I overlooked the paragraph about the similarity between simulated and real point clouds. 

I thought that 50 mm/hr was already heavy enough in the real world but I overlooked the gap between the simulation and reality. Thank you again!

Regards,
Bo Yang
